/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoranapp;

import javax.swing.JOptionPane;

/**
 *
 * @author SNSV
 */
public class Home extends javax.swing.JFrame {

    public String role;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public Home(String role) {
        initComponents();
        this.role = role;
        if(role.equals("admin")){
            BtnEdit.setVisible(true);
            BtnTransaksi.setVisible(true);
        }else if(role.equals("user")){
            BtnEdit.setVisible(false);
            BtnTransaksi.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnLogout = new javax.swing.JButton();
        BtnPesan = new javax.swing.JButton();
        BtnAntrean = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnEdit = new javax.swing.JButton();
        BtnTransaksi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        BtnLogout.setText("Logout");
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 210, 40));
        BtnLogout.getAccessibleContext().setAccessibleDescription("");

        BtnPesan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/place order.png"))); // NOI18N
        BtnPesan.setText("Pesan");
        BtnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 210, 40));

        BtnAntrean.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnAntrean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/generate bill & print.png"))); // NOI18N
        BtnAntrean.setText("Antrean");
        BtnAntrean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAntreanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAntrean, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 210, 40));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Rest-o-CLick");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        BtnEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view edit delete product.png"))); // NOI18N
        BtnEdit.setText("Edit Menu");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 210, 40));

        BtnTransaksi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/View Bills & Order Placed Details.png"))); // NOI18N
        BtnTransaksi.setText("Transaksi");
        BtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin Logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if(a==0){
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesanActionPerformed
        // TODO add your handling code here:
        Pesan pesan = new Pesan();
        pesan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPesanActionPerformed

    private void BtnAntreanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAntreanActionPerformed
        // TODO add your handling code here:
        Antrean antrean = new Antrean();
        antrean.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAntreanActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        EditMenu ed = new EditMenu();
        ed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransaksiActionPerformed
        // TODO add your handling code here:
        RiwayatTransaksi rt = new RiwayatTransaksi();
        rt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAntrean;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnPesan;
    private javax.swing.JButton BtnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
