/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoranapp;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import DataAccessObject.*;
import java.sql.*;
import model.*;


/**
 *
 * @author SNSV
 */
public class Pesan extends javax.swing.JFrame {
    /**
     * Creates new form Home
     */
    DbOperation db;
    ArrayList<Produk> listMenu;
    DefaultTableModel menuTableModel;
    public int selectedRow;

    public Pesan() {
        initComponents();
        db = new DbOperation();
        getData();
    }
    
    public void getData(){
        listMenu = db.lihatDaftarMenu();
        showDataTable();
    }
    
    public void showDataTable(){
        String[] headerTableColumns = {"ID Menu", "Nama ", "Kategori", "Harga"};
        Object[][] menuValue = new Object[listMenu.size()][headerTableColumns.length];
        int i = 0;
        
        for(Produk menu: listMenu) {
            String menuData[] = {menu.id_menu, menu.nama, menu.kategori, menu.harga};
            menuValue[i] = menuData;
            i++;
        };
        
        menuTableModel = new DefaultTableModel(menuValue, headerTableColumns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            };        
        };
        
        menuTable.setModel(menuTableModel);
    }
    
    public void pesanan(){
        this.selectedRow = menuTable.getSelectedRow();
        String id_menu = menuTable.getValueAt(selectedRow, 0).toString();
        String nama = namaTF.getText();
        int JumlahPesanan = Integer.parseInt(jumlahTF.getText().toString());
        int harga = Integer.parseInt(menuTable.getValueAt(selectedRow, 3).toString());
        int Total = JumlahPesanan * harga;
        String TotalHarga = String.valueOf(Total);
        totalTF.setText(String.valueOf(TotalHarga));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JButton();
        BtnAntrean = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        BtnPesan = new javax.swing.JButton();
        namaTF = new javax.swing.JTextField();
        jumlahTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        BtnHitung = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Pesan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        BtnLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        BtnLogout.setText("Logout");
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 210, 40));

        BtnAntrean.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnAntrean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/generate bill & print.png"))); // NOI18N
        BtnAntrean.setText("Antrean");
        BtnAntrean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAntreanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAntrean, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 210, 40));

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        menuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(menuTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 580, 290));

        BtnPesan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add to cart.png"))); // NOI18N
        BtnPesan.setText("Pesan");
        BtnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, -1, -1));
        getContentPane().add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 211, 248, -1));
        getContentPane().add(jumlahTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 284, 248, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama  Pemesan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 176, 248, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jumlah Pesanan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 251, 248, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 324, 248, -1));

        totalTF.setEditable(false);
        totalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTFActionPerformed(evt);
            }
        });
        getContentPane().add(totalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 359, 248, -1));

        BtnHitung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnHitung.setText("Hitung");
        BtnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 418, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin Logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
        if(a==0){
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesanActionPerformed
        // TODO add your handling code here:
        if (selectedRow < 0) {
              JOptionPane.showMessageDialog(this, "Pilih menu yang ingin dipesan terlebih dahulu!");
              return;
        }
        
        try{
            String id_menu = menuTable.getValueAt(selectedRow, 0).toString();
            String nama = namaTF.getText();
            int JumlahPesanan = Integer.parseInt(jumlahTF.getText().toString());
            int harga = Integer.parseInt(menuTable.getValueAt(selectedRow, 3).toString());
            int Total = JumlahPesanan * harga;
            String TotalHarga = String.valueOf(Total);
            db.setDataOrDelete("INSERT INTO pesan(id_menu, nama, harga, JumlahPesanan, TotalHarga) VALUES('"+id_menu+"','"+nama+"','"+harga+"','"+JumlahPesanan+"','"+TotalHarga+"')", "Pesanan Berhasil Dibuat.");
            db.setDataOrDelete("insert into transaksi(nama) values('"+nama+"')", "Data transaksi terkirim ke admin.");
            Antrean antre = new Antrean();
            antre.setVisible(true);
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnPesanActionPerformed

    private void totalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTFActionPerformed

    private void BtnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHitungActionPerformed
        // TODO add your handling code here:
        try{
            pesanan();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Masukkan pesanan dan jumlah pesanan terlebih dahulu");
        }
    }//GEN-LAST:event_BtnHitungActionPerformed

    private void BtnAntreanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAntreanActionPerformed
        // TODO add your handling code here:
        Antrean antrean = new Antrean();
        antrean.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAntreanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAntrean;
    private javax.swing.JButton BtnHitung;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnPesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlahTF;
    private javax.swing.JTable menuTable;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables

}
